AC_PREREQ([2.69])
AC_INIT([gm-gather], [0.1.0], [tkato1219@gmail.com])
AM_INIT_AUTOMAKE([foreign dist-xz no-dist-gzip subdir-objects])
AC_CONFIG_SRCDIR([src/gm-gather.py])
dnl AC_CONFIG_HEADERS([config.h])

AC_PROG_INSTALL
AM_PATH_PYTHON([3.8])  dnl 必要に応じて下限を調整

AC_CONFIG_FILES([
  Makefile
  src/Makefile
])
AC_OUTPUT
